name: 'Markdown Update Badge'
description: 'Update badge when action executed'

inputs:
  mail_sender:
    description: 'mail sender field'
    required: true
    default: ''
  mail_reciever:
    description: 'same as sender'
    required: true
    default: ''
  mail_password:
    description: 'mail password'
    required: true
    default: ''

  status_A:
    description: 'job status A'
    required: true
    default: ''

  status_B:
    description: 'job status b'
    required: true
    default: ''

  status_C:
    description: 'job status c'
    required: true
    default: ''

  status_D:
    description: 'job status d'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
