name: Github action final

on:
  push:
    branches: [ master ]

jobs:

  linter_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Install through npm
        run: npm install

      - name: Lint Code
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  
  cypress_job:
    
    needs: linter_job

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build Production
        run: npm run build
      - name: Cypress Execution
        id: cypress
        continue-on-error: true
        uses: cypress-io/github-action/@v2
        with:
          start: npm start
      - name: Build Result Artifact
        run: |
          echo ${{ steps.cypress.outcome }} > cypress_result.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress_result
          path: ./cypress_result.txt

  add_badge_job:

    needs: cypress_job

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Cypress Result
        uses: actions/download-artifact@v2
        with:
          name: cypress_result
      - name: Set Result as Output
        id: results
        run: |
          echo "::set-output name=cypress_outcome::$(cat cypress_result)"
      - name: Update Badge
        uses: ./.github/actions
        with:
          status: ${{steps.results.outputs.cypress_outcome}}
      - name: Commit and push if changed
        run: | 
          git config --global user.email "readme-bot@epablocs.com"
          git config --global user.name "README-actionBot"
          git add README.md
          git commit -m "Updated Badge from test results" || exit 0
          git push


